export const API_URL = "http://localhost:8080/api/v1";

export const API_ROUTES = {
  LOGIN: "/users/login",
  GET_ALL_MANUFACTURER: "/manufacturers",
  GET_ALL_CATEGORIES: "/categories",
  ADD_PRODUCT: "/products/add",
  GET_ALL_PRODUCTS: "/products",
  GET_A_SINGLE_PRODUCT: "/products/:id",
  CHECKOUT: "/orders",
};

export const APP_ROUTE = {
  HOME: "/",
  PRODUCT: "/product",
  CART: "/cart",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_ADD_PRODUCT: "/admin/add-product",
};

export const ACTION_TYPES_CART = {
  // Selected product
  SELECTED_PRODUCT: "SELECTED_PRODUCT",

  // Adding a product to cart
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",

  // Removing a product from cart
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",

  // Clear out cart
  CLEAR_CART: "CLEAR_CART",

  // Checking out cart
  CHECKOUT_CART_REQUEST: "CHECKOUT_CART_REQUEST",
  CHECKOUT_CART_SUCCESS: "CHECKOUT_CART_SUCCESS",
  CHECKOUT_CART_FAILURE: "CHECKOUT_CART_FAILURE",

  // Increasing quantity of a product in cart
  INCREASE_PRODUCT_QUANTITY: "INCREASE_PRODUCT_QUANTITY",

  // Decreasing quantity of a product in cart
  DECREASE_PRODUCT_QUANTITY: "DECREASE_PRODUCT_QUANTITY",
};

export const ACTION_TYPES_USER = {
  // Login request
  LOGIN_REQUEST: "LOGIN_REQUEST",

  // Login success
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  // Login failure
  LOGIN_FAILURE: "LOGIN_FAILURE",

  // Logout
  LOGOUT: "LOGOUT",
};

export const ACTION_TYPES_MANUFACTURER = {
  FETCH_ALL_MANUFACTURER_REQUEST: "FETCH_ALL_MANUFACTURER_REQUEST",
  FETCH_ALL_MANUFACTURER_SUCCESS: "FETCH_ALL_MANUFACTURER_SUCCESS",
  FETCH_ALL_MANUFACTURER_FAILURE: "FETCH_ALL_MANUFACTURER_FAILURE",
};

export const ACTION_TYPES_CATEGORY = {
  FETCH_ALL_CATEGORY_REQUEST: "FETCH_ALL_CATEGORY_REQUEST",
  FETCH_ALL_CATEGORY_SUCCESS: "FETCH_ALL_CATEGORY_SUCCESS",
  FETCH_ALL_CATEGORY_FAILURE: "FETCH_ALL_CATEGORY_FAILURE",
};

export const ACTION_TYPES_PRODUCT = {
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_A_SINGLE_PRODUCT_REQUEST: "GET_A_SINGLE_PRODUCT_REQUEST",
  GET_A_SINGLE_PRODUCT_SUCCESS: "GET_A_SINGLE_PRODUCT_SUCCESS",
  GET_A_SINGLE_PRODUCT_FAILURE: "GET_A_SINGLE_PRODUCT_FAILURE",
};
